version: '3'
services:
  app:
    image: pdf_parser
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      NODE_ENV: development
    command: npm start
